version: '3'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    links:
      - api
    depends_on:
      - api
  api:
    container_name: api
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db-data:/data/db
    ports:
      - "27017:27017"