version: '3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./services/client.dockerfile
    ports:
      - "3000:3000"
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./services/api.dockerfile
    ports:
      - "4000:4000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./services/db-data:/data/db
    ports:
      - "27017:27017"