version: '3'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db-data:/data/db
    ports:
      - "27017:27017"